services:
  php:
    build:
      context: .
    volumes:
      - ./app:/var/www/html

  nginx:
    image: nginx:1-alpine
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/var/www/html/public
